

-- =====================================================
-- SIMPLE QUESTIONS
-- =====================================================


-- Q1. Display all customers who belong to the North region.

-- WRITE BELOW
SELECT *
FROM customers
WHERE Region = 'North';



-- Q2. Display all products whose price is greater than 20000.

-- WRITE BELOW
SELECT *
FROM products
WHERE Price > 20000;



-- Q3. Find all orders where Quantity is greater than 2
-- and Discount is greater than 0.

-- WRITE BELOW
SELECT *
FROM orders
WHERE Quantity > 2
  AND Discount > 0;



-- Q4. Display all customers whose city is either Jaipur,
-- Delhi or Mumbai.

-- WRITE BELOW
SELECT *
FROM customers
WHERE City IN ('Jaipur', 'Delhi', 'Mumbai');



-- Q5. Find all orders placed during January 2026.

-- WRITE BELOW
SELECT *
FROM orders
WHERE Order_Date BETWEEN '2026-01-01' AND '2026-01-31';



-- =====================================================
-- MODERATE QUESTIONS
-- =====================================================


-- Q6. Find the total Sales generated for each Category.

-- WRITE BELOW
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM orders
GROUP BY Category;



-- Q7. Find the average Profit for each Payment Mode.

-- WRITE BELOW
SELECT
    Payment_Mode,
    AVG(Profit) AS Average_Profit
FROM orders
GROUP BY Payment_Mode;



-- Q8. Find the total Quantity sold for each Product_ID
-- and show only products with total Quantity greater than 10.

-- WRITE BELOW
SELECT
    Product_ID,
    SUM(Quantity) AS Total_Quantity
FROM orders
GROUP BY Product_ID
HAVING SUM(Quantity) > 10;



-- Q9. Find the total Sales for each Sales Channel
-- and sort from highest to lowest.

-- WRITE BELOW
SELECT
    Sales_Channel,
    SUM(Sales) AS Total_Sales
FROM orders
GROUP BY Sales_Channel
ORDER BY Total_Sales DESC;



-- Q10. Display the top 5 products based on total Sales.

-- WRITE BELOW
SELECT
    Product_ID,
    SUM(Sales) AS Total_Sales
FROM orders
GROUP BY Product_ID
ORDER BY Total_Sales DESC
LIMIT 5;



-- =====================================================
-- JOIN QUESTIONS
-- =====================================================


-- Q11. Display Order_ID, Customer_Name, City and Order_Date
-- by joining orders and customers.

-- WRITE BELOW
SELECT
    o.Order_ID,
    c.Customer_Name,
    c.City,
    o.Order_Date
FROM orders o
INNER JOIN customers c
    ON o.Customer_ID = c.Customer_ID;



-- Q12. Display all customers along with their orders.
-- Customers without any order should also be displayed.

-- WRITE BELOW
SELECT
    c.Customer_ID,
    c.Customer_Name,
    o.Order_ID,
    o.Sales
FROM customers c
LEFT JOIN orders o
    ON c.Customer_ID = o.Customer_ID;



-- Q13. Display all products along with their order details.
-- Products without orders should also appear.

-- WRITE BELOW
SELECT
    p.Product_ID,
    p.Product_Name,
    p.Category,
    o.Order_ID,
    o.Quantity
FROM orders o
RIGHT JOIN products p
    ON o.Product_ID = p.Product_ID;



-- Q14. Create every possible combination of
-- Sales Channel and Product Category.

-- WRITE BELOW
SELECT
    s.Sales_Channel,
    p.Category
FROM
    (SELECT DISTINCT Sales_Channel FROM orders) s
CROSS JOIN
    (SELECT DISTINCT Category FROM products) p;



-- Q15. Display each employee along with their manager name.
-- Use SELF JOIN.

-- WRITE BELOW
SELECT
    e.Employee_Name AS Employee,
    m.Employee_Name AS Manager
FROM employees e
LEFT JOIN employees m
    ON e.Manager_ID = m.Employee_ID;



-- =====================================================
-- JOIN + GROUP BY + HAVING
-- =====================================================


-- Q16. Find total Sales generated by each customer.
-- Display Customer_Name and Total_Sales.

-- WRITE BELOW
SELECT
    c.Customer_Name,
    SUM(o.Sales) AS Total_Sales
FROM customers c
INNER JOIN orders o
    ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name;



-- Q17. Find customers whose total Sales are greater than 50000.

-- WRITE BELOW
SELECT
    c.Customer_Name,
    SUM(o.Sales) AS Total_Sales
FROM customers c
INNER JOIN orders o
    ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
HAVING SUM(o.Sales) > 50000;



-- =====================================================
-- SUBQUERY QUESTIONS
-- =====================================================


-- Q18. Find all products whose price is greater than
-- the average price of all products.

-- WRITE BELOW
SELECT *
FROM products
WHERE Price > (
    SELECT AVG(Price)
    FROM products
);



-- Q19. Find all products whose price is greater than
-- the average price of their own category.
-- Use a CORRELATED SUBQUERY.

-- WRITE BELOW
SELECT
    p.Product_Name,
    p.Category,
    p.Price
FROM products p
WHERE p.Price > (
    SELECT AVG(p2.Price)
    FROM products p2
    WHERE p2.Category = p.Category
);



-- Q20. Find the customer who generated the highest
-- total Sales.
-- Display Customer_Name and Total_Sales.

-- WRITE BELOW
SELECT
    c.Customer_Name,
    SUM(o.Sales) AS Total_Sales
FROM customers c
INNER JOIN orders o
    ON c.Customer_ID = o.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
HAVING SUM(o.Sales) = (
    SELECT MAX(Customer_Total)
    FROM (
        SELECT SUM(Sales) AS Customer_Total
        FROM orders
        GROUP BY Customer_ID
    ) AS customer_sales
);